receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      # http:
      #   cors:
      #     allowed_origins:
      #       - "http://*"
      #       - "https://*"
  # httpcheck/frontendproxy:
  #   targets:
  #     - endpoint: http://frontendproxy:${env:ENVOY_PORT}
  # redis:
  #   endpoint: "redis-cart:6379"
  #   collection_interval: 10s

exporters:
  prometheus:
    endpoint: otel-collector:8889
  # debug:
#   otlp:
#     endpoint: "jaeger:4317"
#     tls:
#       insecure: true
#   otlphttp/prometheus:
#     endpoint: "http://prometheus:9090/api/v1/otlp"
#     tls:
#       insecure: true
#   opensearch:
#     logs_index: otel
#     http:
#       endpoint: "http://opensearch:9200"
#       tls:
#         insecure: true

processors:
  batch:

# connectors:
#   spanmetrics:

extensions:
  health_check:
    endpoint: otel-collector:13133

service:
  extensions: [health_check]
  pipelines:
#     traces:
#       receivers: [otlp]
#       processors: [batch]
#       exporters: [otlp, debug, spanmetrics]
     metrics:
        receivers: [otlp]
#       receivers: [httpcheck/frontendproxy, redis, otlp, spanmetrics]
        processors: [batch]
        # exporters: [otlphttp/prometheus, debug]
        exporters: [prometheus]
#     logs:
#       receivers: [otlp]
#       processors: [batch]
#       exporters: [opensearch, debug]
