receivers:
  otlp:
    protocols:
      grpc:
        # endpoint: 0.0.0.0:4317
      http:
        # endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  
  logging:
    verbosity: detailed

  prometheus:
    endpoint: otel-collector:8889

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  file:
    path: /etc/output/logs.json

#   otlp:
#     endpoint: "jaeger:4317"
#     tls:
#       insecure: true
#   otlphttp/prometheus:
#     endpoint: "http://prometheus:9090/api/v1/otlp"
#     tls:
#       insecure: true
#   opensearch:
#     logs_index: otel
#     http:
#       endpoint: "http://opensearch:9200"
#       tls:
#         insecure: true

processors:
  attributes:
    actions:
      - key: evironment
        value: local
        action: insert
  batch:

extensions:
  health_check:
    endpoint: otel-collector:13133

service:
  extensions: [health_check]
  telemetry:
    logs: 
      level: debug
    metrics:
      level: detailed
      address: ":8888"   # http://localhost:8888/metrics
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [debug, otlp, file, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [attributes]
      exporters: [debug, file, logging]
